source 'https://rubygems.org'

gem 'sinatra', github: 'sinatra/sinatra'
gem 'pg'
gem 'activerecord', require: 'active_record'
gem 'sinatra-contrib', require: 'sinatra/contrib/all'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'pry'
gem 'bcrypt'
gem 'sass'
gem 'unicorn'
